---
title: "COVID-19 Dash"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: 
    theme: bootstrap
---

```{r setup, include=FALSE}
  library(flexdashboard)
  library(tidyverse)
  library(ggtext)
  library(ggrepel)
  library(shiny)
  library(shinyWidgets)
  library(tibbletime)

  options(scipen=999)
```

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

# covid
  nyt_st <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv", stringsAsFactors = FALSE)

# census
  load("../data/census.RData")
  states$GEOID <- as.numeric(states$GEOID)
  
# join
  nyt_st <- nyt_st %>%
    left_join(states, by=c("fips" = "GEOID"))
```

Sidebar {.sidebar}
=====================================

```{r}
# select outcome
  selectInput("outcome", label = "Outcome:",
      choices = list("Cases" = "cases", 
                     "Deaths" = "deaths"),
      selected = "cases")

# select states to highlight
  selectizeInput('highlightStates', 'Highlight (multi-select):', 
                 choices = nyt_st %>% distinct(state) %>% arrange(state) %>% pull(state), 
                 multiple = TRUE,
                 selected = "New York")
  
# define rolling window
  sliderInput("roll", label = "Rolling Window", 
              min = 1, 
              max = 14, 
              value = 7,
              step=1)
  
# select axis
  selectInput("axis", label = "Axis:",
      choices = list("Linear" = "linear", 
                     "Exponential" = "exp"),
      selected = "linear")
  
# select per capita
  selectInput("percap", label = "Normalized:",
      choices = list("Per Capita" = "pc", 
                     "None" = "none"),
      selected = "none")
```

Static
=====================================

Column 
-----------------------------------------------------------------------

### United States

```{r}
# deaths
# -------------------------------------------------------------------
  df_deaths <- nyt_st %>%
    mutate(date = lubridate::ymd(date)) %>%
    group_by(date) %>%
    mutate(deaths = sum(deaths)) %>%
    distinct(date, .keep_all = TRUE) %>%
    ungroup() %>%
    mutate(dailyDeaths = c(deaths[1], diff(deaths))) %>%
    ungroup() 

  ggplot(df_deaths) +
    aes(x=date, y=dailyDeaths) +
    geom_col() +
    labs(title = "Daily COVID-19 deaths",
         subtitle = paste(prettyNum(sum(df_deaths$dailyDeaths),
                                    big.mark=","), 
                          "deaths",
                          sep=" "),
         x = "", 
         y = "",
         caption = "Data from *The New York Times*, based on reports from state and local health agencies.") +
    theme_minimal() +
    theme(plot.title.position = "plot",
          plot.title = element_text(size=20),
          plot.subtitle = element_text(size=17),
          axis.title.x = element_text(size=14),
          plot.caption = element_markdown(size=9),
          legend.position = "none")

```


Reactive
=====================================

Column 
-----------------------------------------------------------------------

### State-Level

```{r}
# deaths
# -------------------------------------------------------------------
  df_deaths <- reactive({
    
  roll_mean <- rollify(mean, window=input$roll)
  
  nyt_st %>%
    mutate(date = lubridate::ymd(date)) %>%
    group_by(state) %>%
    mutate(dailyDeaths = c(deaths[1], diff(deaths))) %>%
    mutate(dailyDeathsPerCap = (dailyDeaths/estimate)*100000) %>%
    mutate(dailyDeathsRoll = roll_mean(dailyDeaths)) %>%
    mutate(dailyDeathsRollPerCap = roll_mean(dailyDeathsPerCap)) %>%
    filter(dailyDeaths >= 3) %>%
    mutate(days = 1:n()) %>%
    mutate(label = if_else(days == max(days), 
                           state, 
                           NA_character_)) %>%
    ungroup() %>%
    mutate(highlighted = ifelse(state %in% input$highlightStates, 
                               1, 0)) %>%
    mutate(label = ifelse(highlighted==0, NA_character_, label))
  })


# cases
# -------------------------------------------------------------------
  df_cases <- reactive({
    
  roll_mean <- rollify(mean, window=input$roll)
    
  nyt_st %>%
    group_by(state) %>%
    mutate(dailyCases = c(cases[1], diff(cases))) %>%
    mutate(dailyCasesPerCap = (dailyCases/estimate)*100000) %>%
    mutate(dailyCasesRoll = roll_mean(dailyCases)) %>%
    mutate(dailyCasesRollPerCap = roll_mean(dailyCasesPerCap)) %>%
    filter(dailyCases >= 10) %>%
    mutate(days = 1:n()) %>%
    mutate(label = if_else(days == max(days), 
                           state, 
                           NA_character_)) %>%
    ungroup() %>%
    mutate(highlighted = ifelse(state %in% input$highlightStates, 
                               1, 0)) %>%
    mutate(label = ifelse(highlighted==0, NA_character_, label))
  })


# plots
# -------------------------------------------------------------------
  output$plotState <- renderPlot({
    
# reactive
  df_deaths <- df_deaths()
  df_cases <- df_cases()

# if deaths plot deaths
  if (input$outcome=="deaths") {
    
  p <- ggplot(df_deaths)
    
  # if per capita use PerCap
    if (input$percap=="pc") {
      p <- p +  
        aes(x=days, y=dailyDeathsRollPerCap, 
            group=state,
            color=factor(highlighted),
            size=factor(highlighted)) +
        labs(title = "Daily COVID-19 deaths",
             subtitle = "per 100,000",
             x = "Number of days since 3 daily deaths first recorded", 
             y = "",
             caption = "Data from *The New York Times*, based on reports from state and local health agencies.")
        
  # otherwise use non-PerCap outcome
    } else {
      p <- p +  
        aes(x=days, y=dailyDeathsRoll, 
            group=state,
            color=factor(highlighted),
            size=factor(highlighted)) +
        labs(title = "Daily deaths with coronavirus",
             subtitle = "",
             x = "Number of days since 3 daily deaths first recorded", 
             y = "",
             caption = "Data from *The New York Times*, based on reports from state and local health agencies.")
    }
  
  # apply look and feel of plot
    p <- p + geom_line() +
    scale_color_manual(values = c("grey", "blue")) +
    scale_size_manual(values = c(1, 3)) +
    geom_text_repel(aes(label = label),
                    nudge_x = 1,
                    na.rm = TRUE,
                    size=6) +
    theme_minimal() +
    theme(plot.title.position = "plot",
          plot.title = element_text(size=30),
          plot.subtitle = element_text(size=22),
          axis.title.x = element_text(size=20),
          plot.caption = element_markdown(size=15),
          legend.position = "none")
     
  # if axis exp then log10
    if (input$axis=="exp") {
      p + scale_y_log10()
    } else {
      p
    }
    
    
# otherwise plot cases    
  } else {
    
    p <- ggplot(df_cases) 
    
  # if perCap plot PerCap
    if (input$percap=="pc") {
      p <- p +  
        aes(x=days, y=dailyCasesRollPerCap, 
            group=state,
            color=factor(highlighted),
            size=factor(highlighted)) +
        labs(title = "Daily COVID-19 deaths",
             subtitle = "per 100,000",
             x = "Number of days since 10 daily cases first recorded", 
             y = "",
             caption = "Data from *The New York Times*, based on reports from state and local health agencies.")
      
  # otherwise plot non-PerCap
    } else {
      p <- p +  
        aes(x=days, y=dailyCasesRoll, 
            group=state,
            color=factor(highlighted),
            size=factor(highlighted)) + 
        labs(title = "Daily cases with coronavirus",
             subtitle = "",
             x = "Number of days since 10 daily cases first recorded", 
             y = "",
             caption = "Data from *The New York Times*, based on reports from state and local health agencies.")
    }
    
  # apply look and feel of plot
    p <- p + geom_line() +
    scale_color_manual(values = c("grey", "blue")) +
    scale_size_manual(values = c(1, 3)) +
    geom_text_repel(aes(label = label),
                    nudge_x = 1,
                    na.rm = TRUE,
                    size=6) +
    theme_minimal() +
    theme(plot.title.position = "plot",
          plot.title = element_text(size=30),
          plot.subtitle = element_text(size=22),
          axis.title.x = element_text(size=20),
          plot.caption = element_markdown(size=15),
          legend.position = "none")
    
  # if axis exp then log10
    if (input$axis=="exp") {
      p + scale_y_log10()
    } else {
      p
    }
    
  } # close if deaths/cases
    
  }) # close reactive
  
  plotOutput("plotState", height = "100%")
```


